version: '2'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '10'
    ports:
      - 8000:80
  #Sync backup with S3 amazon
  sync:
    image: silintl/sync-with-s3:1.0.0
    restart: always
    environment:
      - ACCESS_KEY
      - SECRET_KEY
      - BUCKET_LOCATION
      - DESTINATION_PATH
      - CRON_SCHEDULE
      - SOURCE_PATH
    volumes:
      - ../backups:/usr/backups
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '10'
  # backup job 
  backup:
    build: ./ofelia
    restart: always
    environment:
      - BACKUP_DIR
      - DB_NAME
      - DB_MASTER_PASSWORD
      - PREFIX_BACKUP_NAME
    volumes:
      - ./config/backup_odoo.sh:/usr/backup_odoo.sh
      - ../backups:/usr/backups
      - ./config/ofelia.ini:/etc/ofelia/config.ini
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '10'
  db:
    command: -c 'shared_buffers=2048MB' -c 'effective_cache_size=4096'
  web:
    command: --db_host=db -r odoo -w odoo
