version: '2'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '10'
    networks:
      default:
      objects:
        aliases:
          - ${NETWORK_ALIAS}
          
networks:
  default:
    ipam:
      driver: default
      config:
      -
        subnet: ${CUSTOM_SUBNET}
  objects:
    external : true